[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "django-start-automate"
version = "2.0.0a1"
description = "Prepare a new Django project quickly and automatically and more wonderful things that save you time By django start"
readme = "README.md"
requires-python = ">=3.12"
license = {file = "LICENSE"}
authors = [
  {name = "Islam Kamel", email = "islam.kamel@agr.svu.edu.eg"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Framework :: Django",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Code Generators",
    "Topic :: Terminals",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
keywords = [
    "django-start", "django start", "djngo start", "django start project",
    "django project", "django automate", "automate django", "start",
    "start automate", "django build", "django tools", "automate start",
    "djangostart", "django_start", "django-start-automate",
    "django_start_automate", "django start automate", "django script",
    "django cli", "django tool", "python cli", "python tool",
    "python tools", "python script"
]
dependencies = [
    "click",
    "packaging>=23.0,<27.0"
]

[project.urls]
Homepage = "https://github.com/islam-kamel/django-start"

[project.scripts]
django-start = "djstartlib.main:main"
django-version = "djstartlib.version:main"

[tool.setuptools.packages.find]
where = ["src"]
